# Generated by Django 3.1.7 on 2021-03-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schsite.teachers', verbose_name='Учитель'),
        ),
    ]
