# Generated by Django 3.1.7 on 2021-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0003_students_predmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='predmet',
            field=models.ManyToManyField(blank=True, to='schsite.Items', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='urok',
            name='genres',
            field=models.ManyToManyField(blank=True, to='schsite.Students', verbose_name='Пресудствующие ученики'),
        ),
    ]
