# Generated by Django 3.1.7 on 2021-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0004_auto_20210402_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='predmet',
        ),
        migrations.AddField(
            model_name='items',
            name='predmet',
            field=models.ManyToManyField(blank=True, to='schsite.Students', verbose_name='Классы'),
        ),
    ]
