# Generated by Django 3.1.7 on 2021-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0006_auto_20210402_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.PositiveIntegerField(default=5, verbose_name='Класс')),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='klass',
        ),
        migrations.AlterField(
            model_name='items',
            name='predmet',
            field=models.ManyToManyField(blank=True, to='schsite.Klass', verbose_name='Предметы'),
        ),
    ]
