# Generated by Django 3.1.7 on 2021-04-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0007_auto_20210402_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AddField(
            model_name='klass',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название предмета'),
        ),
        migrations.AddField(
            model_name='students',
            name='klas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schsite.klass', verbose_name='Класс'),
        ),
    ]
