# Generated by Django 3.1.7 on 2021-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0009_remove_klass_klass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='title',
        ),
        migrations.AddField(
            model_name='klass',
            name='klass',
            field=models.PositiveIntegerField(default=5, verbose_name='Класс'),
        ),
    ]
