# Generated by Django 3.1.7 on 2021-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0010_auto_20210402_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='klass',
            field=models.CharField(default=5, max_length=100, verbose_name='Класс'),
        ),
    ]
