# Generated by Django 3.1.7 on 2021-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0011_auto_20210402_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='item',
            field=models.ManyToManyField(to='schsite.Items', verbose_name='Предметы'),
        ),
    ]
