# Generated by Django 3.1.7 on 2021-04-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0013_auto_20210403_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urok',
            new_name='kolUrok',
        ),
    ]
