# Generated by Django 3.1.7 on 2021-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0014_auto_20210407_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='url',
            field=models.CharField(default='I dont know', max_length=100, verbose_name='Название предмета на Англ'),
        ),
    ]
