# Generated by Django 3.1.7 on 2021-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0017_auto_20210407_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolurok',
            name='nomer',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер Урока'),
        ),
    ]
