# Generated by Django 3.1.7 on 2021-04-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schsite', '0020_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachers',
            name='it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schsite.items', verbose_name='Предмет'),
        ),
    ]
